{ config, lib, pkgs, ... }:
{
  programs.hyprlock = {
    enable = true;

    settings = {
      # /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
      # Hyprlock config for =< 1080p monitor resolutions                                                        
      # Original config submitted by https://github.com/SherLock707

      # # Sourcing colors generated by wallust
      # source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
      # $Scripts = $HOME/.config/hypr/scripts

      general = {
        grace = 5;
      };

      background = [
        {
          monitor = "";
          path = "$HOME/Pictures/Saved\ Pictures/desktop.png"; # NOTE only png supported for now
        }
      ];

      input-field = [
        {
          monitor = "";
          size = "250, 50";
          outline_thickness = 3;
          dots_size = 0.33; # Scale of input-field height, 0.2 - 0.8
          dots_spacing = 0.15; # Scale of dots' absolute size, 0.0 - 1.0
          dots_center = true;
          outer_color = "$color5";
          inner_color = "$color0";
          font_color = "$color12";
          fade_on_empty = true;
          placeholder_text = "<i>Password...</i>"; # Text rendered in the input box when it's empty.
          hide_input = false;

          position = "0, 80";
          halign = "center";
          valign = "bottom";
        }
      ];

      # Date
      label = [
        {
          monitor = "";
          text = "cmd[update:18000000] echo \"<b> \"$(date +'%A, %-d %B %Y')\" </b>\"";
          color = "$color12";
          font_size = 34;
          font_family = "JetBrains Mono Nerd Font 10";
          position = "0, -80";
          halign = "center";
          valign = "top";
        }
        # Hour-Time
        {
          monitor = "";
          text = "cmd[update:1000] echo \"$(date +\"%H\")\"";
          #    text = cmd[update:1000] echo "$(date +"%I")" #AM/PM
          color = "rgba(255, 185, 0, .6)";
          font_size = 150;
          font_family = "JetBrains Mono Nerd Font Mono ExtraBold";
          position = "0, -200";
          halign = "center";
          valign = "top";
        }
        # Minute-Time
        {
          monitor = "";
          text = "cmd[update:1000] echo \"$(date +\"%M\")\"";
          color = "rgba(255, 255, 255, .6)";
          font_size = 150;
          font_family = "JetBrains Mono Nerd Font Mono ExtraBold";
          position = "0, -450";
          halign = "center";
          valign = "top";
        }

        # Seconds-Time
        {
          monitor = "";
          text = "cmd[update:1000] echo \"$(date +\"%S\")\"";
          #    text = cmd[update:1000] echo "$(date +"%S %p")" #AM/PM
          color = "$color12";
          font_size = 20;
          font_family = "JetBrains Mono Nerd Font Mono ExtraBold";
          position = "0, -450";
          halign = "center";
          valign = "top";
        }

        # User
        {
          monitor = "";
          text = "   $USER";
          color = "$color10";
          font_size = 18;
          font_family = "Inter Display Medium";

          position = "0, 20";
          halign = "center";
          valign = "bottom";
        }
      ];
      
    };
  };
}
