{ config, lib, pkgs, ... }: {

  stylix.targets.hyprlock.enable = false;

  # Fonts for hyprlock
  home.packages = [
    pkgs.nerd-fonts.jetbrains-mono
    pkgs.inter
    pkgs.hypridle
  ];

  home.file = {
    ".config/hypr/hypridle.conf" = {
      enable = true;
      source = ./hypridle.conf;
    };
  };

  # programs.hyprlock = {
  #   enable = true;

  #   settings = {
  #     # /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
  #     # Hyprlock config for =< 1080p monitor resolutions                                                        
  #     # Original config submitted by https://github.com/SherLock707

  #     # # Sourcing colors generated by wallust
  #     # source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
  #     # $Scripts = $HOME/.config/hypr/scripts

  #     general = {
  #       grace = 2;
  #       ignore_empty_input = true;
  #       no_fade_in = false;
  #       disable_loading_bar = false;
  #     };

  #     background = let wallpaper = ../../albertjul/desktop.jpg; in [
  #       {
  #         monitor = "";
  #         path = "${wallpaper}";
  #         blur_passes = 2;
  #         contrast = 0.8916;
  #         brightness = 0.8172;
  #         vibrancy = 0.1696;
  #         vibrancy_darkness = 0.0;
  #       }
  #     ];

  #     input-field = [
  #       {
  #         monitor = "";
  #         size = "250, 60";
  #         outline_thickness = 2;
  #         dots_size = 0.2; # Scale of input-field height, 0.2 - 0.8
  #         dots_spacing = 0.2; # Scale of dots' absolute size, 0.0 - 1.0
  #         dots_center = true;
  #         outer_color = "rgba(0, 0, 0, 0)";
  #         inner_color = "rgba(100, 114, 125, 0.5)";
  #         font_color = "rgb(200, 200, 200)";
  #         fade_on_empty = false;
  #         font_family = "JetBrains Mono Nerd Font";
  #         placeholder_text = "<i><span foreground=\"##ffffff99\">Hi, $USER</span></i>";
  #         hide_input = false;
  #         position = "0, -290";
  #         halign = "center";
  #         valign = "center";
  #       }
  #     ];

  #     label = [
  #       # Date
  #       {
  #         monitor = "";
  #         text = "cmd[update:18000000] echo \"<b> \"$(date +'%A, %-d %B %Y')\" </b>\"";
  #         color = "rgb(${config.lib.stylix.colors.base0C})";
  #         font_size = 34;
  #         font_family = "JetBrains Mono Nerd Font 10";
  #         position = "0, -80";
  #         halign = "center";
  #         valign = "top";
  #       }
  #       # Hour-Time
  #       {
  #         monitor = "";
  #         text = "cmd[update:1000] echo \"$(date +\"%H\")\"";
  #         #    text = cmd[update:1000] echo "$(date +"%I")" #AM/PM
  #         color = "rgb(${config.lib.stylix.colors.base05})";
  #         font_size = 150;
  #         font_family = "JetBrains Mono Nerd Font Mono ExtraBold";
  #         position = "0, -200";
  #         halign = "center";
  #         valign = "top";
  #       }
  #       # Minute-Time
  #       {
  #         monitor = "";
  #         text = "cmd[update:1000] echo \"$(date +\"%M\")\"";
  #         color = "rgb(${config.lib.stylix.colors.base06})";
  #         font_size = 150;
  #         font_family = "JetBrains Mono Nerd Font Mono ExtraBold";
  #         position = "0, -450";
  #         halign = "center";
  #         valign = "top";
  #       }

  #       # Seconds-Time
  #       {
  #         monitor = "";
  #         text = "cmd[update:1000] echo \"$(date +\"%S\")\"";
  #         #    text = cmd[update:1000] echo "$(date +"%S %p")" #AM/PM
  #         color = "rgb(${config.lib.stylix.colors.base0C})";
  #         font_size = 20;
  #         font_family = "JetBrains Mono Nerd Font Mono ExtraBold";
  #         position = "0, -450";
  #         halign = "center";
  #         valign = "top";
  #       }

  #       # User
  #       {
  #         monitor = "";
  #         text = "   $USER";
  #         color = "rgb(${config.lib.stylix.colors.base0A})";
  #         font_size = 18;
  #         font_family = "Inter Display Medium";

  #         position = "0, 20";
  #         halign = "center";
  #         valign = "bottom";
  #       }
  #     ];

  #   };
  # };
}
